### ISSUE TITLE
ALA protected species layers

### ISSUE THREAD

**Issue by paul121** [Regen-Digital/farm_regen_digital#16]
https://support.ala.org.au/support/solutions/articles/6000200049-how-to-embed-a-species-map-in-a-web-page-using-ala-wms-services

Swift parrot, regent honey eater, Quoll and Koala

**Comment by Kristin404** [comment]
Koala - https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/e9d6fbbd-1505-4073-990a-dc66c930dad6
Regent honeyeater - https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/31869a0e-2ce5-40be-b6f6-c0231a48b414
Swift parrot - https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/4cb195fd-b127-44cb-ad85-a62d224e9a96
Eastern Quoll - https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/52149285-a12a-4085-a285-b41af5ba3ce3

**Comment by paul121** [comment]
Layers are working!

![Screenshot from 2022-10-19 12-35-09](https://user-images.githubusercontent.com/3116995/196787019-6a4ff0c7-0f20-45db-a4d4-f60c828f22e2.png)

**Comment by Kristin404** [comment]
That is very cool!
