### ISSUE TITLE
Threatened species action plan

### ISSUE THREAD

**Issue by paul121** [Regen-Digital/farm_regen_digital#19]
Follow up to #16

**Comment by Kristin404** [comment]
ok here we go the first of our 100 priority species - 
all data in _Priority Threatened Species Tab_ - AASF Control Sheet https://docs.google.com/spreadsheets/d/1etSuudtvD06w8WaTucbzeS2ZbEFqDeVcalqF0JN7edo/edit#gid=1953165126

**Comment by Kristin404** [comment]
**Birds**

Australasian Bittern, Botaurus poiciloptilus - https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/dba78701-cae9-4afb-a41a-6697c52c5e34.json

Black-eared Miner, Manorina melanotis  - https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/ca7db878-07f9-4c93-a611-5d0aa7dcf594.json

Carnaby’s Cockatoo, Zanda latirostris - https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/4072e7ce-7ca4-4112-a9fa-c49a0f0ddd4d.json

Christmas Island Goshawk, Accipiter hiogaster natalis - https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/bf9a9b37-8c34-44c2-a65b-69c46015d38d.json

Eastern Curlew, Numenius madagascariensis - https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/5ff29bca-f02f-468f-9f96-9ae956015e01.json

Golden-shouldered Parrot, Alwal Psephotus chrysopterygius - https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/3ff9c7bc-fa07-4977-ada0-83f979488c7e.json

Hooded Plover (eastern), Thinornis cucullatus cucullatus - https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/1ebf8ec6-9aee-4b58-8789-0be73eb97b2f

Malleefowl, Leipoa ocellata | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/c44c9098-c4fc-4f64-884c-e367389b194f.json

Night Parrot, Pezoporus occidentalis | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/c630f3b0-528a-4686-a2a1-73113135f214.json

Noisy Scrub-bird, Atrichornis clamosus - https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/2c8750a3-60ab-4cbf-ac00-c5c5bb7b28a8.json

Orange-bellied Parrot, Neophema chrysogaster - https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/88653999-1e2f-47d1-87fa-1f6d3e47ffb8.json

Plains-wanderer, Pedionomus torquatus - https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/30b4b2e5-0d5b-46cb-bddb-a2137a35fa2c.json

Princess Parrot, Polytelis alexandrae - https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/be7a08f5-387f-4156-91e2-77f0d3d09d8c.json

Red Goshawk, Erythrotriorchis radiatus - https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/390a23b8-0097-4a2c-b068-283d2d4bd21f.json

Red-tailed Black Cockatoo (SE), Calyptorhynchus banksii graptogyne - https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/f8ecc7e3-47fc-494a-907c-c444ce843e73.json

Regent Honeyeater, Anthochaera phrygia - https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/31869a0e-2ce5-40be-b6f6-c0231a48b414.json

Swift Parrot, Lathamus discolor | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/4cb195fd-b127-44cb-ad85-a62d224e9a96.json

Western Ground Parrot, Kyloring Pezoporus flaviventris - https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/bfeb0f1a-5581-4034-ba30-e330fe233af6.json

White-throated Grasswren, Yirlinkirrkirr Amytornis woodwardi | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/efee8cb8-20c0-4d35-84b5-c0e904723697.json

**Comment by Kristin404** [comment]
**Mammals**

Brush-tailed Rock-wallaby, Petrogale penicillata - https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/7a7a2817-26e7-44bd-bb34-1dc9c1ed4d38.json

Central Rock-rat, Antina Zyzomys pedunculatus | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/33ab483d-5bec-45a4-857a-f0a1bbd36bfe.json

Chuditch, Western Quoll Dasyurus geoffroii | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/a2260672-36df-48be-8a9e-d85a77237ba5.json

Eastern Quoll, Luaner Dasyurus viverrinus | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/52149285-a12a-4085-a285-b41af5ba3ce3.json

Gilbert’s Potoroo, Ngilkat Potorous gilbertii | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/4d8d03c2-8249-4b97-a0bf-d71be2aaf651.json

Greater Bilby, Macrotis lagotis | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/3814d122-c95f-467f-a3a2-2b269931b74f.json

Kangaroo Island Echidna, Tachyglossus aculeatus multiaculeatus | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/e9289876-b550-4278-a4db-336bd5f75e6a.json

Koala (Qld, NSW, ACT) Phascolarctos cinereus | https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/e9d6fbbd-1505-4073-990a-dc66c930dad6

Leadbeater’s Possum Gymnobelideus leadbeateri | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/6119c642-08ad-403e-b8c9-215814f63ee3.json

Mountain Pygmy-possum, Burramys parvus | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/3f17cf84-982a-48f2-9500-e44dcd30710a.json

New Holland Mouse, Pookila Pseudomys novaehollandiae | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/47a50ee8-7678-4d8e-8f8a-e11d12a46ec5.json

Northern Brushtail Possum, Trichosurus vulpecula arnhemensis | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/568f23f7-0700-452a-bf04-a5cd9a8b6fc6.json

Northern Hairy-nosed Wombat, Yaminon Lasiorhinus krefftii | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/a3b32e6c-b91f-4a75-ab77-6cb240848e69.json

Northern Hopping-mouse, Woorrentinta Notomys aquilo | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/6ac36ddd-54f5-4ab4-9ad4-1a5405307c26.json

Northern Quoll, Dasyurus hallucatus | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/5d7aeda8-2ec1-4111-830e-847f34321f88.json

Numbat, Myrmecobius fasciatus | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/6c72d199-f0f1-44d3-8197-224a2f7cff5f.json

Quokka, Setonix brachyurus | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/6e0e413a-e59c-413b-9d16-3d20b1bab707.json

Spectacled Flying-fox, Pteropus conspicillatus | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/27d443cb-290b-4d53-8010-5e230f840d67.json

Southern Bent-wing Bat, Miniopterus orianae bassanii | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/98dbf664-a454-4472-81bf-325fa41a1876.json

Western Ringtail Possum, Pseudocheirus occidentalis | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/df5c846f-14a9-4f0a-93f4-92710cdb4cd7.json

Platypus | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/ac61fd14-4950-4566-b384-304bd99ca75f.json

**Comment by Kristin404** [comment]
**Fish**

Freshwater Sawfish, Pristis pristis | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/4fc5aabd-2174-4c12-87ff-5e69007ecea2.json

Maugean Skate, Zearaja maugeana | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/0d9d194f-ab8d-46da-a835-bb9c9fbda130.json

Murray Hardyhead, Craterocephalus fluviatilis | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/50568ccf-e05e-4d55-885d-5fcf41bb17ef.json

Red Handfish, Thymichthys politus | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/14e659fa-e5c0-446c-aa07-c748889c8495.json

Redfin Blue-eye, Scaturiginichthys vermeilipinnis | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/df4e5f69-d850-4d5b-8182-b525024c2902.json

Stocky Galaxias, Galaxias tantangara | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/13a9b415-8fcb-4000-93d4-d2247439e1e9.json

Swan Galaxias, Galaxias fontanus | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/e34d1659-1a1b-4d85-842e-3665edf32938.json

**Comment by Kristin404** [comment]
**Frogs**

Growling Grass Frog, Southern Bell Frog Litoria raniformis | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/6e63311a-159e-44d5-ae3f-a63dfc0a829a.json

Kroombit Tinker Frog, Taudactylus pleione | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/5908f2e8-065f-48ea-a45a-ae155bf66246.json

Mountain Frog, Philoria kundagungan | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/fcb2e700-8046-4556-94bd-78d188dadd9c.json

Mountain-top Nursery-frog, Cophixalus monticola | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/cfedc2d5-7752-4326-8c5c-ed9463576257.json

Southern Corroboree Frog, Pseudophryne corroboree | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/1a3bc394-a748-4755-a6b8-98dd42da48db.json

White-bellied Frog, Anstisia alba | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/57576674-05b0-4981-a3d3-a26a0998da29.json

**Comment by Kristin404** [comment]
**Reptiles**

Arnhem Land Gorges Skink, Bellatorias obiri | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/2afc8501-f330-4973-84d9-94dc817d793c.json

Bellinger River Snapping Turtle, Wollumbinia georgesi | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/4f95257b-a79e-452a-bc1e-9f512d8fd878.json

Canberra Earless Dragon, Tympanocryptis lineata | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/49122cf6-e123-47f9-8ee4-a649373a2a47.json

Collared Delma, Adorned Delma, Delma torquata | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/92ec5b2c-1f8f-4d29-b088-77bacaeeb99f.json

Great Desert Skink, Tjakura, Warrarna, Mulyamiji, Liopholis kintorei | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/08ac895d-b350-43d6-8810-65459a59f072.json

Pygmy Blue-tongue Lizard, Tiliqua adelaidensis | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/a70c19ab-7d61-4e14-91ff-c81e54cbea9f.json

Western Swamp Turtle, Pseudemydura umbrina | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/8308a376-50a5-483b-ac9f-39d702b817ec.json

Yinnietharra Rock-dragon, Ctenophorus yinnietharra | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/025a3de1-31b9-49a5-adfc-176af86e1bcc.json

**Comment by Kristin404** [comment]
**Invertebrates** 

Ammonite Snail, Ammoniropa vigens | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/8c3ea615-895f-4e1b-b904-b803f70d5747.json

Eltham Copper Butterfly, Paralucia pyrodiscus lucida | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/a667ea63-754b-4bb9-a8d0-33dde1017441.json

Giant Gippsland Earthworm, Megascolides australis | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/301ed996-2d89-41a7-92fb-c5d7e5709f9c.json

Glenelg Freshwater Mussel, Hyridella glenelgensis | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/60f9442f-c8b5-4228-861a-0d938b8b6613.json

Kangaroo Island Assassin Spider, Zephyrarchaea austini | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/9a446b93-6444-47df-935f-fc42fe5962b0.json

Lord Howe Island Phasmid, Dryococelus australis | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/3757e8d2-7623-4849-a261-eba989512d18.json

Margaret River Burrowing Crayfish, Engaewa pseudoreducta | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/fe837421-d280-4cbc-b4e7-defe299d9ce0.json

Mount Lidgbird Charopid Land Snail, Pseudocharopa ledgbirdi | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/39f4563a-1898-49d3-a92a-9c4aa04186b5.json

Pink Underwing Moth, Phyllodes imperialis smithersi | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/be90dde5-17ae-4f85-bf2a-4bc3f4f67542.json

Tasmanian Giant Freshwater Crayfish, Astacopsis gouldi | https://bie-ws.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/fe773527-b516-4861-845f-0cd3746b4f98.json

**Comment by Kristin404** [comment]
**Plants**

Adamson’s Blown-grass, Lachnagrostis adamsonii | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/taxon/apni/51291365.json

Angle-stemmed Myrtle, Gossia gonoclada | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2912922.json

Arckaringa Daisy, Olearia arckaringensis | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2901236.json

Bolivia Hill Rice-flower, Pimelea venosa | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2891541.json

Border Ranges Lined Fern, Antrophyum austroqueenslandicum | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/taxon/apni/51293661.json

Bulberin Nut, Macadamia jansenii | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2904937.json

Carrington Falls Pomaderris, Pomaderris walshii | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2909534.json

Davies’ Waxflower, Phebalium daviesii | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2897721.json

Foote’s Grevillea, Grevillea calliantha | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2903139.json

Forked Spyridium, Spyridium furculentum | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2920269.json

Giant Andersonia, Andersonia axilliflora | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2886487.json

Gorge Rice-flower, Pimelea cremnophila | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2889688.json

Graveside Leek-orchid, Prasophyllum taphanyx | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/taxon/apni/51409980.json
Imlay Mallee, Eucalyptus imlayensis | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2899202.json

King Blue-grass, Dichanthium queenslandicum | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2901362.json

Lax Leek Orchid, Prasophyllum laxum | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/taxon/apni/51409799.json

Little Mountain Palm, Lepidorrhachis mooreana | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2918196.json

MacDonnell Ranges Cycad, Macrozamia macdonnellii | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2917134.json

Narrow-leaf Eremophila, Eremophila subangustifolia | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/name/apni/50591078.json

Native Guava, Rhodomyrtus psidioides | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2901415.json

Scaly-butt Mallee, Eucalyptus leprophloia | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2896677.json

Small-flowered Snottygobble, Persoonia micranthera | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/7829750.json

Smooth Davidson’s Plum, Davidsonia johnsonii | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2915538.json
Stiff Groundsel, Senecio behrianus | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2898428.json

Stirling Range Dryandra, Banksia montana | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2900376.json

Tangled Wattle, Acacia volubilis | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2905924.json

Waddy, Waddi, Waddy-wood, Birdsville Wattle, Acacia peuce | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2906202.json

Wollemi Pine, Wollemia nobilis | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2899238.json

Wongan Eriostemon, Philotheca wonganensis | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2912677.json

Woods Well Spyridium, Spyridium fontis-woodii | https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2897404.json

**Comment by Kristin404** [comment]
Priority species Lists END - all data in _Priority Threatened Species Tab_ - AASF Control Sheet https://docs.google.com/spreadsheets/d/1etSuudtvD06w8WaTucbzeS2ZbEFqDeVcalqF0JN7edo/edit#gid=1953165126

**Comment by paul121** [comment]
I've made some good progress on this & hope to publish this soon. I learned that we are specifically using the BioCache API from ALA to see "Occurrences":

- https://docs.ala.org.au/#2-occurrences
- https://docs.ala.org.au/openapi/index.html?urls.primaryName=occurrences#/Mapping/getOccurrencesInformation

There is also an existing Biocache search tool that is *wicked* cool, albeit quite complex: https://biocache.ala.org.au/#tab_spatialSearch

I've been able to reference this and am working on implementing some enhanced features for this. Notably:
- Create a `taxa:{name}` filter to limit to desired taxonomies (grouped by categories as above)
- Color based on the taxonomy name, returns different colors in the WMS layer
- Query the color legend they return with WMS data
- Query occurrences at a given point when map is clicked

There is also an API endpoint to calculate the number of occurrences for each taxa within a given bounds and has helper methods to query this within a state or region bounds. This would be useful to get quick quantitative numbers on # species have been seen in a given area.

![Screenshot from 2023-02-22 18-18-29](https://user-images.githubusercontent.com/3116995/220808168-5c31232f-31dd-4fee-b58a-b20b81525666.png)

**Comment by paul121** [comment]
@Kristin404 @RohanClarke have a look at this, let me know if I'm headed in the wrong direction...

https://user-images.githubusercontent.com/3116995/220830517-7e211f9f-2be1-45ce-a172-30b1fc3fd1e3.mp4

**Comment by RohanClarke** [comment]
This is so cool @paul121 !!!
Exactly in the right direction...

**Comment by Kristin404** [comment]
SOOO COOL! Love your work @paul121
