### ISSUE TITLE
Replace farmOS logo with Regen Digital logo

### ISSUE THREAD

**Issue by paul121** [Regen-Digital/farm_regen_digital#2]
- Make sure Gin theme changes won't effect this

**Comment by mstenta** [comment]
I've done this in another custom module - sharing for reference:

```php
/**
 * Implements hook_install().
 */
function farm_regen_digital_install() {
  $path = \Drupal::service('extension.list.module')->getPath('regen_digital');
  $config = \Drupal::configFactory()->getEditable('gin.settings');
  $config->set('logo.path', $path . '/logo.png');
  $config->save();
}

/**
 * Implements hook_install().
 */
function farm_regen_digital_uninstall() {
  $path = \Drupal::service('extension.list.module')->getPath('farm_ui_theme');
  $config = \Drupal::configFactory()->getEditable('gin.settings');
  $config->set('logo.path', $path . '/logo.png');
  $config->save();
}
```

Just need to add this to `regen_digital.install` and add a `logo.png` file.

**Comment by mstenta** [comment]
Oh the above code will need to be tweaked to work with Gin beta: https://www.drupal.org/project/farm/issues/3270561#comment-14450506

Edit: I updated the comment above accordingly.

**Comment by mstenta** [comment]
Also updated the code snippet above to use `\Drupal::service('extension.list.module')->getPath()` instead of the deprecated `drupal_get_path()`. I will be doing this in farmOS core as well.

**Comment by paul121** [comment]
Thanks @mstenta - this is now all done via https://github.com/paul121/farm_regen_digital/commit/8ef6fe2b0c3d15eb65653c1f2deaf30e0fcce62d
