### ISSUE TITLE
Deploy v1.0.2

### ISSUE THREAD

**Issue by paul121** [Regen-Digital/farm_regen_digital#3]
Hey @mstenta can you confirm that v1.0.2 is deployed? https://github.com/paul121/farm_regen_digital/blob/1.x/CHANGELOG.md#102-2022-04-22

I'm trying to access the profile settings page but get a 404 error not a 403 access denied which makes me think it hasn't been deployed. https://test.regen-digital.farm/farm/settings/profiles

Apologies if I forgot to ping you when I tagged v1.0.2 - I think I'll create an issue to request this from here on out!

**Comment by mstenta** [comment]
It was not deployed. But it is now!

Yes we should work out a standard procedure for deployments. A new issue assigned to me makes sense as a first step...
